Iter5
nikishin42/shortener pull request #5
Opened 2023-08-22 10:02 UTC by nikishin42

2023-08-22 20:28 UTC, popoffvg requested changes

2023-08-22 20:28 UTC, popoffvg commented on cmd/shortener/pkg/abbreviator/abbreviator.go
> +	CreateID(data []byte, base string) (string, error)
[minor]

Интерфейс стоит размещать в месте использования или отдельным пакетом. Размещение интерфейса рядом с реализацией имеет смысл только для библиотек, где изменение контракта влечет изменине клиентов гарантированно. 

Для слоя доменной логики не всегда это так

2023-08-22 20:28 UTC, popoffvg commented on cmd/shortener/pkg/abbreviator/abbreviator.go
> +type AbbreviatorI interface {
[minor]

I не принято писать на конце

2023-08-22 20:28 UTC, popoffvg commented on cmd/shortener/server/handlers.go
> +	bodyData, err := io.ReadAll(r.Body)
[major]

Тело нужно закрывать всегда

2023-08-22 20:28 UTC, popoffvg commented on cmd/shortener/server/handlers.go
> +	if id, ok := s.Storage.GetID(fullURL); ok {
[minor]

Последовательность вызовов домена в хендлере обычно признак не самого удачного дизайна, лучше вынести в отдельный слой бизнес-логики.

2023-08-22 20:28 UTC, popoffvg commented on cmd/shortener/server/server.go
> +	log.Fatal(http.ListenAndServe(s.Config.Address, s.Router))
[major]
Стоит всегда проверять на ошибку ErrServerClosed, которая возращается всегда при завершении работы сервера

2023-08-23 14:56 UTC, nikishin42 commented on cmd/shortener/pkg/abbreviator/abbreviator.go
> +	CreateID(data []byte, base string) (string, error)
вынес в отдельный пакет, переименовал без I в конце

2023-08-23 14:56 UTC, nikishin42 commented on cmd/shortener/pkg/abbreviator/abbreviator.go
> +type AbbreviatorI interface {
переименовал

2023-08-23 14:56 UTC, nikishin42 commented on cmd/shortener/server/handlers.go
> +	bodyData, err := io.ReadAll(r.Body)
закрыл тело в дефере

2023-08-23 15:11 UTC, nikishin42 commented on cmd/shortener/server/handlers.go
> +	if id, ok := s.Storage.GetID(fullURL); ok {
создал слой бл, вынес в бл, на уровне сервис леера оставил валидацию входных параметров, логирование ошибок, сет статусов респонса

2023-08-23 15:11 UTC, nikishin42 commented on cmd/shortener/server/server.go
> +	log.Fatal(http.ListenAndServe(s.Config.Address, s.Router))
добавил проверку

2023-08-23 18:06 UTC, popoffvg approved these changes

2023-08-28 12:27 UTC, merged